/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gisintegration;

import java.awt.event.MouseWheelEvent;
import java.io.IOException;
import java.net.URL;
import java.util.List;
import javax.swing.JOptionPane;
import org.geotools.data.ows.Layer;
import org.geotools.data.wms.WebMapServer;
import org.geotools.geometry.jts.ReferencedEnvelope;
import org.geotools.map.MapContent;
import org.geotools.map.WMSLayer;
import org.geotools.ows.ServiceException;
import org.geotools.renderer.lite.StreamingRenderer;
import org.geotools.swing.action.InfoAction;
import org.geotools.swing.action.NoToolAction;
import org.geotools.swing.action.PanAction;
import org.geotools.swing.action.ResetAction;
import org.geotools.swing.action.ZoomInAction;
import org.geotools.swing.action.ZoomOutAction;
import org.geotools.swing.control.JMapStatusBar;
import org.geotools.swing.wms.WMSLayerChooser;

/**
 *
 * @author rufino
 */
public class TagaBukidWMS extends javax.swing.JPanel {

    /**
     * Creates new form TagaBukidWMS
     */
    public TagaBukidWMS() throws IOException, ServiceException {
        URL capabilitiesURL = new URL("http://localhost:8090/geoserver/test/wms");
        if( capabilitiesURL == null ){
            System.exit(0); // canceled
        }
        WebMapServer wms = new WebMapServer( capabilitiesURL );        
        
        List<Layer> wmsLayers = WMSLayerChooser.showSelectLayer( wms );
        if( wmsLayers == null ){
            JOptionPane.showMessageDialog(null, "Could not connect - check url");
            System.exit(0);
        }
        MapContent map = new MapContent();
        map.setTitle("ETRACS Geo");

        for( Layer wmsLayer : wmsLayers ){
            WMSLayer displayLayer = new WMSLayer(wms, wmsLayer );
            map.addLayer(displayLayer);
        }
        initComponents();
        mapPane.setRenderer( new StreamingRenderer() );
        mapPane.setMapContent( map );
        mapPane.setVisible(true);
    }
    // somewhere in your code...
//        double clickToZoom = 0.1;  // 1 wheel click is 10% zoom
//
//        // wheel event handler
//        public void handleMouseWheelEvent(MouseWheelEvent ev) {
//           int clicks = ev.getWheelRotation();
//           // -ve means wheel moved up, +ve means down
//           int sign = (clicks < 0 ? -1 : 1);
//
//           ReferencedEnvelope env = mapPane.getDisplayArea();
//           double width = env.getWidth();
//           double delta = width * clickToZoom * sign;
//
//           env.expandBy(delta);
//           mapPane.setDisplayArea(env);
//           mapPane.repaint();
//        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapPane = new org.geotools.swing.JMapPane();
        jToolBar1 = new javax.swing.JToolBar();
        ToolbarPointerButton = new javax.swing.JButton(new NoToolAction(mapPane));
        jSeparator1 = new javax.swing.JToolBar.Separator();
        ToolbarResetButton = new javax.swing.JButton(new ResetAction(mapPane));
        jSeparator2 = new javax.swing.JToolBar.Separator();
        ToolbarZoomInButton = new javax.swing.JButton(new ZoomInAction(mapPane));
        ToolbarZoomOutButton = new javax.swing.JButton(new ZoomOutAction(mapPane));
        jSeparator3 = new javax.swing.JToolBar.Separator();
        ToolbarInfoButton = new javax.swing.JButton(new InfoAction(mapPane));
        ToolbarPanButton = new javax.swing.JButton(new PanAction(mapPane));
        jMapStatusBar2 = JMapStatusBar.createDefaultStatusBar(mapPane);

        javax.swing.GroupLayout mapPaneLayout = new javax.swing.GroupLayout(mapPane);
        mapPane.setLayout(mapPaneLayout);
        mapPaneLayout.setHorizontalGroup(
            mapPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        mapPaneLayout.setVerticalGroup(
            mapPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        ToolbarPointerButton.setFocusable(false);
        ToolbarPointerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ToolbarPointerButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(ToolbarPointerButton);
        jToolBar1.add(jSeparator1);

        ToolbarResetButton.setFocusable(false);
        ToolbarResetButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ToolbarResetButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(ToolbarResetButton);
        jToolBar1.add(jSeparator2);

        ToolbarZoomInButton.setFocusable(false);
        ToolbarZoomInButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ToolbarZoomInButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(ToolbarZoomInButton);

        ToolbarZoomOutButton.setFocusable(false);
        ToolbarZoomOutButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ToolbarZoomOutButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(ToolbarZoomOutButton);
        jToolBar1.add(jSeparator3);

        ToolbarInfoButton.setFocusable(false);
        ToolbarInfoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ToolbarInfoButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(ToolbarInfoButton);

        ToolbarPanButton.setFocusable(false);
        ToolbarPanButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ToolbarPanButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(ToolbarPanButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(mapPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jMapStatusBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mapPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMapStatusBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ToolbarInfoButton;
    private javax.swing.JButton ToolbarPanButton;
    private javax.swing.JButton ToolbarPointerButton;
    private javax.swing.JButton ToolbarResetButton;
    private javax.swing.JButton ToolbarZoomInButton;
    private javax.swing.JButton ToolbarZoomOutButton;
    private org.geotools.swing.control.JMapStatusBar jMapStatusBar2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private org.geotools.swing.JMapPane mapPane;
    // End of variables declaration//GEN-END:variables
}
